[build-system]
requires = ["setuptools>=66.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rna-predict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"

# Core dependencies
dependencies = [
    "numpy>=2.2.3",
    "torch>=2.6.0",
]

# If you have optional (dev) dependencies:
[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "coverage>=7.6.12",
    "flake8>=7.1.2",
    "gitchangelog>=3.0.4",
    "isort>=6.0.1",
    "mkdocs>=1.6.1",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
]

# If you want a console script:
[project.scripts]
rna_predict = "rna_predict.__main__:main"
